### ISSUE TITLE
Re-enable disabled wifi-iface

### ISSUE THREAD

**Issue by andrasbari** [jhenzely/owrf#1]
It could be improvement to make a delayed wifi scan. And compare to owned ones. If some of the scanned ssid equals to one of the configured ssid, it can be re-enabled the interface.

list available ssids:
`uci show wireless | grep ".ssid='" | sed "s/^[^']*'\([^']*\)'.*/\1/"`

scan wifi and get ssids:
`iwinfo wlan0 scan | grep ESSID | sed 's/^[^"]*"\([^"]*\)".*/\1/'`

**Comment by jhenzely** [comment]
Thank You.
Yes, work on the "re-enable interface" feature is currently in progress.
Currently very busy with other stuff, but of course, it is simple and I hope it will be implemented soon.

**Comment by andrasbari** [comment]
Yesterday I made a simple script based on your sources. It seems to be working.
You can download from: http://sonus.tech/openwrt/sta.sh

**Comment by jhenzely** [comment]
Very nice !
Thank You for contribution. Not tested, but it looks good.
About the automated installation, I will deploy one web server soon.
So, no problem with wget and https.

**Comment by andrasbari** [comment]
https://www.arubacloud.com/free-trial.aspx
https://www.arubacloud.com/vps/virtual-private-server-range.aspx
I have got 2 small vps in CZ and I installed the VestaCP for it: http://vestacp.com/
About 20 minutes to full working webserver.

**Comment by jhenzely** [comment]
Thanks.
I have virtual server, so no need for free trial VPS ;)

**Comment by jhenzely** [comment]
I wrote the code which now has functionality of self "re-enabling" or failback, whatever...
https://github.com/jhenzely/owrf/blob/master/compleate_testing.sh

Currently I don't see issue, but extensive stability and fulctionality tests will be performed.

Finally, at this time, from my perspective this project is going to the end.
